#!/usr/bin/ruby

require 'rubygems'
require 'ansi'

class String
  include ANSI::Mixin
end

spec = Gem::Specification::load("bookbinder.gemspec")
puts "Building Gem version #{spec.version.to_s.yellow} at #{Time.now.strftime('%b %e, %l:%M %p').yellow}..."
system('gem build bookbinder.gemspec')
system("gem install bookbinder-#{spec.version}.gem --ignore-dependencies --no-document")