#!/bin/bash

set -e

pushd `dirname $0` > /dev/null
BOOKBINDER_BIN_PATH=`pwd`
popd > /dev/null

ln -s ${BOOKBINDER_BIN_PATH}/bindery /usr/local/bin/
echo "linked ${BOOKBINDER_BIN_PATH}/bindery to /usr/local/bin/bindery"
